apiVersion: v1
kind: ConfigMap
metadata:
  name: kommande-config
  namespace: kommande
data:
  MONGO_URI: "mongodb://mongodb:27017"
  DB_NAME: "kommande"
  PORT: "8080"
  BASE_URL: "https://kommande.internal.rayq.app"
  OIDC_ISSUER: "https://keycloak.internal.rayq.app/realms/home"
  OIDC_CLIENT_ID: "kommande"
  OIDC_REDIRECT_URL: "https://kommande.internal.rayq.app/auth/callback"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
