apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kommande-oidc-secret
  namespace: kommande
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: kommande-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: keycloak
        property: kommande-client-secret
