apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: controller-manager
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: github
        property: pat
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-runner-notify
  namespace: github-runner
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: github-runner-notify
    creationPolicy: Owner
  data:
    - secretKey: pat_expiry
      remoteRef:
        key: github
        property: pat-expiry
    - secretKey: discord_webhook
      remoteRef:
        key: github
        property: discord-webhook
