version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - unparam

formatters:
  default: none
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/therayquaza

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
  max-issues-per-linter: 0
  max-same-issues: 0
