apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: argocd-exception
  namespace: kyverno
spec:
  exceptions:
  - policyName: require-security-context
    ruleNames:
    - require-non-root
    - require-seccomp
    - autogen-require-non-root
    - autogen-require-seccomp
  match:
    any:
    - resources:
        namespaces: ["argocd"]
        selector:
          matchLabels:
            app.kubernetes.io/name: argocd-redis
    - resources:
        namespaces: ["argocd"]
        selector:
          matchLabels:
            app.kubernetes.io/name: argocd-notifications-controller
