kind: Deployment
apiVersion: apps/v1
metadata:
  name: pix-deployment
  namespace: pix
  labels:
    app: pix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pix
  template:
    metadata:
      labels:
        app: pix
    spec:
      containers:
        - name: pix
          image: ghcr.io/therayquaza/home-cluster/pix:0.1.2@sha256:33910dc951d55371563260b1d059b16d894744f01ed6d82e59c7d21de7d53086
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
      # imagePullSecrets:
      #   - name: ghcr
