name: Build - games-backend

on:
  pull_request:
    paths:
      - apps/games/backend/**
      - .github/workflows/apps/games-backend/build.yaml
      - .github/workflows/templates/build.yaml

jobs:
  build:
    uses: ./.github/workflows/templates/build.yaml
    with:
      context: apps/games/backend
      image-name: ghcr.io/therayquaza/home-cluster/games-backend
      push: false
      platforms: linux/amd64
    permissions:
      contents: read
      packages: read
