apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged-containers
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: disallow-privileged
    match:
      any:
      - resources:
          kinds: ["Pod"]
    exclude:
      any:
      - resources:
          namespaces: ["kube-system"]
    skipBackgroundRequests: true
    validate:
      message: "Privileged containers are not allowed"
      allowExistingViolations: true
      foreach:
      - list: "request.object.spec.[containers, initContainers][]"
        deny:
          conditions:
            any:
            - key: "{{ element.securityContext.privileged || false }}"
              operator: Equals
              value: true
