name: Build - pix

on:
  pull_request:
    paths:
      - apps/pix/**
      - .github/workflows/apps/pix/build.yaml
      - .github/workflows/templates/build.yaml

jobs:
  build:
    uses: ./.github/workflows/templates/build.yaml
    with:
      context: apps/pix
      image-name: ghcr.io/therayquaza/home-cluster/pix
      push: false
      platforms: linux/amd64
    permissions:
      contents: read
      packages: read
