name: Lint - pix

on:
  pull_request:
    paths:
      - apps/pix/**
      - .hadolint.yaml
      - .github/workflows/apps/pix/lint.yaml
      - .github/workflows/templates/lint-docker.yaml

jobs:
  docker:
    uses: ./.github/workflows/templates/lint-docker.yaml
    with:
      dockerfile: apps/pix/Dockerfile
    permissions:
      contents: read

  govet:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: false
      - name: go vet
        run: go vet .
        working-directory: apps/pix
