name: Lint - pix

on:
  pull_request:
    paths:
      - apps/pix/**
      - .github/workflows/apps/pix/lint.yaml
  push:
    branches:
      - main
    paths:
      - apps/pix/**
      - .github/workflows/apps/pix/lint.yaml

jobs:
  govet:
    runs-on: [home-cluster]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: false
      - name: go vet
        run: go vet .
        working-directory: apps/pix
