name: Security - pix

on:
  pull_request:
    paths:
      - apps/pix/**
      - .github/workflows/apps/pix/security.yaml
      - .github/workflows/templates/security-trivy.yaml

jobs:
  trivy:
    uses: ./.github/workflows/templates/security-trivy.yaml
    with:
      scan-type: fs
      target: apps/pix
    permissions:
      contents: read
      security-events: write
