name: Lint - Ansible

on:
  pull_request:
    paths:
      - ansible/**
      - .github/workflows/infra/lint-ansible.yaml

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ansible/ansible-lint@v24
        with:
          working_directory: ansible/
