apiVersion: v1
kind: ConfigMap
metadata:
  name: dinks-config
  namespace: dinks
data:
  PORT: "8080"
  MONGO_DB: "dinks"
  BASE_URL: "https://dinks.internal.rayq.app"
  OIDC_ISSUER: "https://keycloak.internal.rayq.app/realms/home"
  OIDC_CLIENT_ID: "dinks-web"
  OIDC_MOBILE_CLIENT_ID: "dinks-mobile"
  OIDC_REDIRECT_URL: "https://dinks.internal.rayq.app/auth/callback"
