apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dinks-secret
  namespace: dinks
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: dinks-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef: { key: dinks, property: db-password }
    - secretKey: MONGO_URI
      remoteRef: { key: dinks, property: mongo-uri }
    - secretKey: JWT_SECRET
      remoteRef: { key: dinks, property: jwt-secret }
    - secretKey: MONGO_KEYFILE
      remoteRef: { key: dinks, property: mongo-keyfile }
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef: { key: keycloak, property: dinks-web-client-secret }
