name: Build - kommande

on:
  pull_request:
    paths:
      - apps/kommande/**
      - .github/workflows/apps/kommande/build.yaml
      - .github/workflows/templates/build.yaml

jobs:
  build:
    uses: ./.github/workflows/templates/build.yaml
    with:
      context: apps/kommande
      image-name: ghcr.io/therayquaza/home-cluster/kommande
      push: false
      platforms: linux/amd64
    permissions:
      contents: read
      packages: read
