name: Lint - kommande

on:
  pull_request:
    paths:
      - apps/kommande/**
      - .golangci.yml
      - .hadolint.yaml
      - .github/workflows/apps/kommande/lint.yaml
      - .github/workflows/templates/lint-go.yaml
      - .github/workflows/templates/lint-docker.yaml

jobs:
  go:
    uses: ./.github/workflows/templates/lint-go.yaml
    with:
      working-directory: apps/kommande
    permissions:
      contents: read

  docker:
    uses: ./.github/workflows/templates/lint-docker.yaml
    with:
      dockerfile: apps/kommande/Dockerfile
    permissions:
      contents: read
