name: Lint - kommande

on:
  pull_request:
    paths:
      - apps/kommande/**
      - .golangci.yml
      - .github/workflows/apps/kommande/lint.yaml
      - .github/workflows/templates/lint-go.yaml
  push:
    branches:
      - main
    paths:
      - apps/kommande/**
      - .golangci.yml
      - .github/workflows/apps/kommande/lint.yaml
      - .github/workflows/templates/lint-go.yaml

jobs:
  go:
    uses: ./.github/workflows/templates/lint-go.yaml
    with:
      working-directory: apps/kommande
    permissions:
      contents: read
