name: Security - kommande

on:
  pull_request:
    paths:
      - apps/kommande/**
      - .github/workflows/apps/kommande/security.yaml
      - .github/workflows/templates/security-trivy.yaml

jobs:
  trivy:
    uses: ./.github/workflows/templates/security-trivy.yaml
    with:
      scan-type: fs
      target: apps/kommande
    permissions:
      contents: read
      security-events: write
