apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: idp
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: keycloak
        property: admin-password
    - secretKey: postgresql-password
      remoteRef:
        key: keycloak
        property: postgresql-password
