---
- name: restart networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: restart resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
