apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dinks
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: dinks
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
  sources:
    - repoURL: https://github.com/TheRayquaza/home-cluster.git
      targetRevision: main
      path: k8s/dinks
