apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: actions-runner-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  sources:
  - repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.14.2
    destination:
      namespace: actions-runner-system
    helm:
      releaseName: gha-runner-scale-set-controller
      values: |
        replicaCount: 1

        serviceAccount:
          create: true

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

        podSecurityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

  - repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.14.2
    destination:
      namespace: github-runner
    helm:
      releaseName: home-cluster
      values: |
        githubConfigUrl: https://github.com/TheRayquaza/home-cluster

        runnerScaleSetName: home-cluster

        namespaceOverride: github-runner

        githubConfigSecret: github-token

        minRunners: 1
        maxRunners: 5

        containerMode:
          type: dind

        controllerServiceAccount:
          namespace: actions-runner-system
          name: gha-runner-scale-set-controller-gha-rs-controller

  - repoURL: https://github.com/TheRayquaza/home-cluster.git
    targetRevision: main
    path: k8s/github-runner
    destination:
      namespace: github-runner