kind: Kustomization
resources:
  - apps.yaml
  - argocd.yaml
  - cilium.yaml
  - dinks.yaml
  - kata.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - vault.yaml
  - gateway.yaml
  - system.yaml
  - local-path-provisioner.yaml
  - kyverno.yaml
  - trivy.yaml
  - falco.yaml
#  - pinchflat.yaml
#  - immich.yaml
  - uptime-kuma.yaml
  - pix.yaml
  - kommande.yaml
  - games.yaml
  - idp.yaml
  - policy-reporter.yaml
  - github-runner.yaml
