apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-backend
  namespace: games
  labels:
    app: games-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: games-backend
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: backend
          image: ghcr.io/therayquaza/home-cluster/games-backend:latest@sha256:3d22540fdf0d06959dfa047ce3790dac2eb09a0f0b3295e012648703db8404f4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: games-config
            - secretRef:
                name: games-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /api/games
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/games
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30

