apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-frontend
  namespace: games
  labels:
    app: games-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games-frontend
  template:
    metadata:
      labels:
        app: games-frontend
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: frontend
          image: ghcr.io/therayquaza/home-cluster/games-frontend:v0.1.2@sha256:a68276a48990ef1a780cf0073b042ba4ba090d921e7a10a9b5994d9bd596bab6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 30
            failureThreshold: 3
