apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-backend
  namespace: games
  labels:
    app: games-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: games-backend
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: backend
          image: ghcr.io/therayquaza/home-cluster/games-backend:v0.1.0@sha256:f1279aa5d226d5ef27b5a41f0bfd15329c0289095d3c05f3f36bfe51a181216f
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: games-config
            - secretRef:
                name: games-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /api/games
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/games
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30

