apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: games-oidc-secret
  namespace: games
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: games-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: keycloak
        metadataPolicy: None
        property: games-client-secret
