apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: games-route
  namespace: games
spec:
  parentRefs:
    - name: private-gateway
      namespace: default
      sectionName: games-https
  hostnames:
    - games.internal.rayq.app
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: games-backend-service
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /ws
      backendRefs:
        - name: games-backend-service
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: games-frontend-service
          port: 80
