name: Build - games-frontend

on:
  push:
    tags:
      - "games-frontend/v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      context: apps/games/frontend
      image-name: ghcr.io/therayquaza/home-cluster/games-frontend
      tag-prefix: "games-frontend/"
    permissions:
      contents: read
      packages: write
