name: Build - kommande

on:
  push:
    tags:
      - "kommande/v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      context: apps/kommande
      image-name: ghcr.io/therayquaza/home-cluster/kommande
      tag-prefix: "kommande/"
    permissions:
      contents: read
      packages: write
