name: CI - Apps

on:
  pull_request:
    paths:
      - apps/**
      - .hadolint.yaml
      - .github/workflows/ci-apps.yaml
      - .github/workflows/reusable-app-ci.yaml
      - .github/workflows/reusable-build.yaml
      - .github/workflows/reusable-lint-docker.yaml
      - .github/workflows/reusable-layer-analysis.yaml
      - .github/workflows/reusable-security-trivy.yaml
  push:
    branches:
      - main
    paths:
      - apps/**
      - .hadolint.yaml
      - .github/workflows/ci-apps.yaml
      - .github/workflows/reusable-app-ci.yaml
      - .github/workflows/reusable-build.yaml
      - .github/workflows/reusable-lint-docker.yaml
      - .github/workflows/reusable-layer-analysis.yaml
      - .github/workflows/reusable-security-trivy.yaml

jobs:
  pix:
    uses: ./.github/workflows/reusable-app-ci.yaml
    with:
      context: apps/pix
      image-name: ghcr.io/therayquaza/home-cluster/pix
      dockerfile: apps/pix/Dockerfile
      scan-target: apps/pix
    permissions:
      contents: read
      packages: read
      security-events: write

  games-frontend:
    uses: ./.github/workflows/reusable-app-ci.yaml
    with:
      context: apps/games/frontend
      image-name: ghcr.io/therayquaza/home-cluster/games-frontend
      dockerfile: apps/games/frontend/Dockerfile
      scan-target: apps/games/frontend
    permissions:
      contents: read
      packages: read
      security-events: write

  games-backend:
    uses: ./.github/workflows/reusable-app-ci.yaml
    with:
      context: apps/games/backend
      image-name: ghcr.io/therayquaza/home-cluster/games-backend
      dockerfile: apps/games/backend/Dockerfile
      scan-target: apps/games/backend
    permissions:
      contents: read
      packages: read
      security-events: write

  kommande:
    uses: ./.github/workflows/reusable-app-ci.yaml
    with:
      context: apps/kommande
      image-name: ghcr.io/therayquaza/home-cluster/kommande
      dockerfile: apps/kommande/Dockerfile
      scan-target: apps/kommande
    permissions:
      contents: read
      packages: read
      security-events: write