name: Lint - games-backend

on:
  pull_request:
    paths:
      - apps/games/backend/**
      - .golangci.yml
      - .github/workflows/apps/games-backend/lint.yaml
      - .github/workflows/templates/lint-go.yaml
  push:
    branches:
      - main
    paths:
      - apps/games/backend/**
      - .golangci.yml
      - .github/workflows/apps/games-backend/lint.yaml
      - .github/workflows/templates/lint-go.yaml

jobs:
  go:
    uses: ./.github/workflows/reusable-lint-go.yaml
    with:
      working-directory: apps/games/backend
    permissions:
      contents: read
