name: Lint - Kubernetes

on:
  pull_request:
    paths:
      - k8s/**
      - .kube-linter.yaml
      - .github/workflows/lint-k8s.yaml
      - .github/workflows/reusable-lint-k8s.yaml
  push:
    branches:
      - main
    paths:
      - k8s/**
      - .kube-linter.yaml
      - .github/workflows/lint-k8s.yaml
      - .github/workflows/reusable-lint-k8s.yaml

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint-k8s.yaml
    permissions:
      contents: read