name: Lint - Ansible

on:
  pull_request:
    paths:
      - ansible/**
      - .github/workflows/lint-ansible.yaml
  push:
    branches:
      - main
    paths:
      - ansible/**
      - .github/workflows/lint-ansible.yaml

jobs:
  ansible-lint:
    runs-on: [home-cluster]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Install collection dependencies
        run: ansible-galaxy collection install ansible.posix community.general

      - name: Run ansible-lint
        run: ansible-lint .
        working-directory: ansible/
