name: Lint - Terraform

on:
  pull_request:
    paths:
      - terraform/**
      - .tflint.hcl
      - .github/workflows/lint-terraform.yaml
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .tflint.hcl
      - .github/workflows/lint-terraform.yaml

jobs:
  fmt:
    runs-on: [home-cluster]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Check formatting
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/terraform" \
            -w /terraform \
            hashicorp/terraform:1.12.2 \
            fmt -check -recursive terraform/

  tflint:
    runs-on: [home-cluster]
    permissions:
      contents: read
    strategy:
      matrix:
        module:
          - aws
          - cloudflare
          - keycloak
          - vault-auth
          - vault-oidc
          - vault-secrets
    steps:
      - uses: actions/checkout@v7

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Init tflint
        run: tflint --init
        working-directory: terraform/${{ matrix.module }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tflint
        run: tflint
        working-directory: terraform/${{ matrix.module }}
