name: Publish - pix

on:
  push:
    tags:
      - "pix/v*"

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      context: apps/pix
      image-name: ghcr.io/therayquaza/home-cluster/pix
      push: true
      tag-prefix: "pix/"
    permissions:
      contents: read
      packages: write

  attest:
    needs: build
    runs-on: [home-cluster]
    permissions:
      id-token: write
      attestations: write
      packages: write
    steps:
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ghcr.io/therayquaza/home-cluster/pix
          subject-digest: ${{ needs.build.outputs.digest }}
          push-to-registry: true
