name: Renovate

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v46.1.14
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-app-token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
